Repository geoschem/geos-chem, pull requests merged in 2021-11, with the labels that each got.

#985 [PULL REQUEST] Fix numerical issues that halted GCHP benchmark simulations (closes geoschem/gchp #170)
  GeosCore/sulfate_mod.F90
  KPP/fullchem/rateLawUtilFuncs.F90
Labels: bug, KPP / Chem Mechanisms

#983 [PULL REQUEST] Update run/shared/cleanRunDir.sh to remove additional GCHP logs (closes #982)
  run/shared/cleanRunDir.sh
Labels: feature, config-files

#986 [PULL REQUEST] Bug fix: Remove second underscore from state_chm Hg fields (closes #957)
  Headers/state_chm_mod.F90
Labels: bug

#952 [PULL REQUEST] Bug fix: Replace single precision constants in fullchem.eqn w/ doubles (closes #951)
  KPP/aciduptake/aciduptake.eqn
  KPP/fullchem/fullchem.eqn
  KPP/fullchem/gckpp_Rates.F90
Labels: bug, KPP / Chem Mechanisms

#1017 Fix outdated path in GCHP fullchem config file ExtData.rc
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
Labels: bug, GCHP

#1008 Added a 'DefaultCollection' to GCHP
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: feature, config-files

#992 [PULL REQUEST] Add PM10 diagnostic according to suggestions from Aerosols WG (Closes #958)
  GeosCore/aerosol_mod.F90
  Headers/state_diag_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: feature, diagnostics
