Repository geoschem/geos-chem, pull requests merged in 2021-03, with the labels that each got.

#661 [PULL REQUEST] Bug fixes for GEOS-Chem Classic dry-run simulations
  GeosCore/ucx_mod.F90
  Headers/state_chm_mod.F90
  Headers/state_diag_mod.F90
  run/GCClassic/createRunDir.sh
  run/shared/download_data.py
Labels: dry-run

#663 [PULL REQUEST] Remove useless computations from KPP rate-law routines + OMP Collapse
  GeosCore/fast_jx_mod.F90
  GeosCore/flexchem_mod.F90
  GeosCore/isorropiaII_mod.F90
  GeosCore/ucx_mod.F90
  Headers/physconstants.F90
  KPP/OHreact_parser.py
  KPP/build_mechanism.sh
  KPP/custom/custom.eqn
  KPP/custom/gckpp.kpp
  KPP/custom/gckpp_Integrator.F90
  KPP/custom/gckpp_Precision.F90
  KPP/fullchem/CMakeLists.txt
  KPP/fullchem/fullchem.eqn
  KPP/fullchem/gckpp.kpp
  KPP/fullchem/gckpp.map
  KPP/fullchem/gckpp_Function.F90
  KPP/fullchem/gckpp_Global.F90
  KPP/fullchem/gckpp_HetRates.F90
  KPP/fullchem/gckpp_Initialize.F90
  KPP/fullchem/gckpp_Integrator.F90
  KPP/fullchem/gckpp_Jacobian.F90
  KPP/fullchem/gckpp_JacobianSP.F90
  KPP/fullchem/gckpp_LinearAlgebra.F90
  KPP/fullchem/gckpp_Monitor.F90
  KPP/fullchem/gckpp_Parameters.F90
  KPP/fullchem/gckpp_Precision.F90
  KPP/fullchem/gckpp_Rates.F90
  KPP/fullchem/gckpp_Util.F90
  KPP/fullchem/print_het.H
  KPP/int/.gitignore
  KPP/int/gckpp_Integrator_lsodes.F90
  KPP/int/gckpp_Integrator_radau5.F90
  KPP/int/gckpp_Integrator_rosenbrock.F90
  KPP/int/gckpp_Integrator_rosenbrock.f90ADJ.X
  KPP/int/gckpp_Integrator_runge_kutta.F90
Labels: KPP-for-GEOS-Chem, feature

#664 [PULL REQUEST] Fix typo in call to HetIxCycleSSA (in KPP/fullchem/gckpp_HetRates.F90)
  KPP/fullchem/gckpp_HetRates.F90
Labels: bug

#651 [PULL REQUEST] Remove all code for RRTMG binary diagnostics
  GeosCore/diag3.F90
  GeosCore/diag_mod.F90
  GeosCore/fast_jx_mod.F90
  GeosCore/gamap_mod.F90
  GeosCore/initialize.F90
  GeosCore/input_mod.F90
  GeosCore/ndxx_setup.F90
  GeosCore/rrtmg_rad_transfer_mod.F90
  Headers/CMN_DIAG_mod.F90
  Headers/input_opt_mod.F90
  run/GCClassic/input.geos.templates/input.geos.CH4
  run/GCClassic/input.geos.templates/input.geos.CO2
  run/GCClassic/input.geos.templates/input.geos.Hg
  run/GCClassic/input.geos.templates/input.geos.POPs
  run/GCClassic/input.geos.templates/input.geos.TransportTracers
  run/GCClassic/input.geos.templates/input.geos.aerosol
  run/GCClassic/input.geos.templates/input.geos.fullchem
  run/GCClassic/input.geos.templates/input.geos.tagCH4
  run/GCClassic/input.geos.templates/input.geos.tagCO
  run/GCClassic/input.geos.templates/input.geos.tagO3
Labels: diagnostics

#615 [PULL REQUEST] Extraction of J-rates from KPP via planeflight diagnostic
  GeosCore/planeflight_mod.F90
Labels: diagnostics, feature

#495 [PULL REQUEST] 12.9.2+simplify calc met
  GeosCore/calc_met_mod.F90
Labels: feature
