Repository geoschem/geos-chem, pull requests merged in 2022-10, with the labels that each got.

#1400 [PULL REQUEST] Fix incorrect RETURN for deallocation in Cleanup_Vdiff
  GeosCore/vdiff_mod.F90
Labels: bug

#1433 Update the README file that gets placed in the rundir for 14.0.0
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCH4
Labels: documentation

#1437 Bug fix: disable analytical inversion by default for CH4 simulations
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCH4
Labels: bug, config-files / rundir, specialty simulations

#1451 Update units metadata for State_Met%AirNumDen (should be molec cm-3); Closes #1441
  Headers/state_met_mod.F90
Labels: bug, diagnostics

#1446 [FEATURE REQUEST] Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1468 Fix typo preventing the ND51 satellite diagnostic from turning on
  GeosCore/input_mod.F90
Labels: bug

#1456 Improve GCHP crash error message in run scripts
  run/GCHP/runScriptSamples/gchp.batch_job.sh
  run/GCHP/runScriptSamples/gchp.local.run
  run/GCHP/runScriptSamples/operational_examples/harvard_cannon/gchp.run
  run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/gchp.pleiades.run
Labels: GCHP

#1473 Update Restart collection in HISTORY.rc to include BXHEIGHT and TROPLEV for all simulations
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.POPs
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.metals
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCO
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagO3
Labels: diagnostics
