Repository geoschem/geos-chem, pull requests merged in 2022-09, with the labels that each got.

#1279 Feature/user registration: optionally register first time users with dynamodb database
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
Labels: feature

#1385 Revert GCClassic_Output/14.0.0 data to GCClassic_Output/13.0.0
  run/shared/settings/gmao_hemco.txt
Labels: bug, config-files / rundir

#1389 Add special treatment for MOH in dry deposition if not over land
  GeosCore/drydep_mod.F90
Labels: bug

#1387 Bug fix: revert GC-Classic pressure fixer to v13.3
  GeosCore/pjc_pfix_mod.F90
Labels: bug, GC-Classic only

#1299 Add missing entries for POG1, POG2, and pFe to HEMCO_Config.rc
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: bug
