Repository geoschem/geos-chem, pull requests merged in 2023-12, with the labels that each got.

#2050 Update GEOS-Chem Classic rundir scripts to read restart file paths from download_data.yml
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCClassic/setupForRestarts.sh
  run/shared/download_data.py
  run/shared/download_data.yml
Labels: dry-run, config-files / rundir, no-diff-to-benchmark, bugfix

#2015 Move aerosol_mod.F90 arrays to State_Chm%AerMass object
  CHANGELOG.md
  GeosCore/CMakeLists.txt
  GeosCore/aerosol_mod.F90
  GeosCore/carbon_mod.F90
  GeosCore/cleanup.F90
  GeosCore/diagnostics_mod.F90
  GeosCore/oasave.F90
  Headers/CMakeLists.txt
  Headers/aermass_container_mod.F90
  Headers/state_chm_mod.F90
  Interfaces/GCClassic/main.F90
  Interfaces/GCHP/gchp_chunk_mod.F90
Labels: feature, Aerosols WG

#2060 TOMAS updates: Capability to run in GCHP, NetCDF diagnostics, and other fixes
  CHANGELOG.md
  GeosCore/aero_drydep.F90
  GeosCore/aerosol_mod.F90
  GeosCore/carbon_mod.F90
  GeosCore/chemistry_mod.F90
  GeosCore/diag3.F90
  GeosCore/drydep_mod.F90
  GeosCore/dust_mod.F90
  GeosCore/emissions_mod.F90
  GeosCore/fullchem_mod.F90
  GeosCore/gamap_mod.F90
  GeosCore/gc_environment_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hcoi_gc_diagn_mod.F90
  GeosCore/input_mod.F90
  GeosCore/mixing_mod.F90
  GeosCore/ndxx_setup.F90
  GeosCore/seasalt_mod.F90
  GeosCore/sulfate_mod.F90
  GeosCore/tomas_mod.F90
  GeosCore/wetscav_mod.F90
  Headers/state_chm_mod.F90
  Headers/state_diag_mod.F90
  KPP/custom/custom.eqn
  KPP/fullchem/CHANGELOG_fullchem.md
  KPP/fullchem/fullchem.eqn
  KPP/fullchem/fullchem_HetStateFuncs.F90
  KPP/fullchem/gckpp_Function.F90
  KPP/fullchem/gckpp_Jacobian.F90
  KPP/fullchem/gckpp_JacobianSP.F90
  KPP/fullchem/gckpp_LinearAlgebra.F90
  KPP/fullchem/gckpp_Monitor.F90
  KPP/fullchem/gckpp_Parameters.F90
  KPP/fullchem/gckpp_Util.F90
  run/CESM/HEMCO_Config.rc
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/createRunDir.sh
  run/GCHP/setCommonRunSettings.sh.template
  run/WRF/fullchem/HEMCO_Config.rc
  run/shared/setupConfigFiles.sh
  run/shared/species_database.yml
  run/shared/species_database_tomas.yml
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCHP/integrationTestCreate.sh
  test/parallel/GCClassic/parallelTestCompile.sh
  test/shared/commonFunctionsForTests.sh
Labels: Aerosols WG

#2061 Add missing units in comments of KPP/fullchem/commonIncludeVars.sh
  CHANGELOG.md
  KPP/fullchem/commonIncludeVars.H
Labels: documentation, KPP / chem mechanisms, no-diff-to-benchmark, bugfix

#2063 Fix unit conversion code for TOMAS following merge with 14.2.3
  GeosCore/fullchem_mod.F90
Labels: specialty simulations, bugfix

#2069 Reduce timers to essential list only
  CHANGELOG.md
  GeosCore/carbon_gases_mod.F90
  GeosCore/chemistry_mod.F90
  GeosCore/fullchem_mod.F90
  GeosCore/mercury_mod.F90
  GeosCore/mixing_mod.F90
  Interfaces/GCClassic/main.F90
Labels: structural, no-diff-to-benchmark

#1522 Add Cloud-J as new default photolysis option
  CHANGELOG.md
  GeosCore/CMakeLists.txt
  GeosCore/cldj_interface_mod.F90
  GeosCore/fast_jx_mod.F90
  GeosCore/fjx_interface_mod.F90
  GeosCore/fullchem_mod.F90
  GeosCore/gamap_mod.F90
  GeosCore/gc_environment_mod.F90
  GeosCore/input_mod.F90
  GeosCore/mercury_mod.F90
  GeosCore/photolysis_mod.F90
  GeosCore/ucx_mod.F90
  Headers/CMakeLists.txt
  Headers/input_opt_mod.F90
  Headers/phot_container_mod.F90
  Headers/state_diag_mod.F90
  Headers/state_met_mod.F90
  Interfaces/GCClassic/main.F90
  Interfaces/GCHP/gchp_chunk_mod.F90
  run/GCClassic/createRunDir.sh
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCHP/createRunDir.sh
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GEOS/geoschem_config.yml
  test/shared/commonFunctionsForTests.sh
Labels: feature, never stale, Chemistry WG

#2058 GEOS-Chem Transport Tracers simulation GEOS
  Interfaces/GCHP/Chem_GridCompMod.F90
  Interfaces/GCHP/gchp_historyexports_mod.F90
  Interfaces/GEOS/Includes_After_Run.H
  Interfaces/GEOS/Includes_Before_Run.H
  Interfaces/GEOS/geos_interface.F90
  run/GEOS/GEOSCHEMchem_ExtData.yaml
  run/GEOS/TransportTracers/GEOSCHEMchem_ExtData.rc
  run/GEOS/TransportTracers/GEOSCHEMchem_ExtData.yaml
  run/GEOS/TransportTracers/GEOSCHEMchem_GridComp.rc
  run/GEOS/TransportTracers/HEMCO_Config.rc
  run/GEOS/TransportTracers/HEMCO_DiagnFile.rc
  run/GEOS/TransportTracers/HISTORY.rc
  run/GEOS/TransportTracers/geoschem_config.yml
Labels: no-diff-to-benchmark, interface to external model, specialty simulations

#2084 Use rundir (not absolute path) to select the executable file for integration and parallel tests
  CHANGELOG.md
  test/integration/GCClassic/integrationTestExecute.sh
  test/integration/GCHP/integrationTestExecute.sh
  test/parallel/GCClassic/parallelTestExecute.sh
Labels: testing / benchmarking, no-diff-to-benchmark, bugfix
