Repository geoschem/geos-chem, pull requests merged in 2023-08, with the labels that each got.

#1895 Impose boundary conditions at every timestep in GC-Classic nested-grid simulations
  CHANGELOG.md
  GeosCore/CMakeLists.txt
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hco_utilities_gc_mod.F90
  GeosCore/set_boundary_conditions_mod.F90
  Interfaces/GCClassic/main.F90
Labels: nested grid simulation, bugfix

#1899 Restore IONO2 uptake on tropospheric sulfate aerosols
  KPP/fullchem/fullchem_RateLawFuncs.F90
Labels: bug, KPP / chem mechanisms

#1923 Update code in carbon_gases_mod.F90 for consistency with config file updates from PR #1916
  CHANGELOG.md
  GeosCore/carbon_gases_mod.F90
Labels: specialty simulations, bugfix

#1925 Update dimension to 2D from 3D for OCEAN_CONC for Hg simulations
  CHANGELOG.md
  GeosCore/mercury_mod.F90
  run/shared/settings/gcap2_hemco.txt
  run/shared/settings/gmao_hemco.txt
Labels: config-files / rundir, specialty simulations, bugfix

#1929 Bugfix to initialize advected species to background values if not in restart
  CHANGELOG.md
  Interfaces/GCHP/Chem_GridCompMod.F90
Labels: GCHP, bugfix

#1920 Hotfix: Exit routine INIT_PHOTOLYSIS before calling SET_AER when doing dry-run simulations
  CHANGELOG.md
  GeosCore/photolysis_mod.F90
Labels: dry-run, runtime, bugfix
