Repository geoschem/geos-chem, pull requests merged in 2023-07, with the labels that each got.

#1794 Run directory updates for integration tests
  CHANGELOG.md
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/parallelTest.sh
  test/GCClassic/.gitignore
  test/GCClassic/README.md
  test/GCClassic/integration/commonFunctionsForTests.sh
  test/GCClassic/parallel/commonFunctionsForTests.sh
  test/GCHP/.gitignore
  test/GCHP/README.md
  test/GCHP/integration/commonFunctionsForTests.sh
  test/README.md
  test/difference/README.md
  test/difference/diffTest.sh
  test/integration/GCClassic/README.md
  test/integration/GCClassic/README.testroot.md
  test/integration/GCClassic/integrationTest.sh
  test/integration/GCClassic/integrationTestCompile.sh
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCClassic/integrationTestExecute.sh
  test/integration/GCHP/README.md
  test/integration/GCHP/README.testroot.md
  test/integration/GCHP/integrationTest.sh
  test/integration/GCHP/integrationTestCompile.sh
  test/integration/GCHP/integrationTestCreate.sh
  test/integration/GCHP/integrationTestExecute.sh
  test/integration/README.md
  test/parallel/GCClassic/README.md
  test/parallel/GCClassic/README.testroot.md
  test/parallel/GCClassic/parallelTest.sh
  test/parallel/GCClassic/parallelTestCompile.sh
  test/parallel/GCClassic/parallelTestCreate.sh
  test/parallel/GCClassic/parallelTestExecute.sh
  test/parallel/README.md
  test/shared/README.md
  test/shared/commonFunctionsForTests.sh
Labels: feature, testing / benchmarking, zero-diff

#1799 Explicitly define tagCH4 simulations instead of making assumption based on number of species
  CHANGELOG.md
  GeosCore/chemistry_mod.F90
  GeosCore/emissions_mod.F90
  GeosCore/gamap_mod.F90
  GeosCore/gc_environment_mod.F90
  GeosCore/global_ch4_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hco_utilities_gc_mod.F90
  GeosCore/hcoi_gc_diagn_mod.F90
  GeosCore/input_mod.F90
  GeosCore/mercury_mod.F90
  GeosCore/mixing_mod.F90
  GeosCore/ocean_mercury_mod.F90
  Headers/input_opt_mod.F90
  Headers/state_chm_mod.F90
  Headers/state_diag_mod.F90
Labels: zero-diff, specialty simulations

#1856 move REF_TRF file from OtherAnthropogenic to Oil
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCH4
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: bug, specialty simulations, Carbon gases WG

#1857 Update minimum KPP version required for the fullchem mechanism from 2.5.0 to 3.0.0
  CHANGELOG.md
  KPP/fullchem/CHANGELOG_fullchem.md
  KPP/fullchem/fullchem.kpp
Labels: feature, KPP / chem mechanisms, zero-diff

#1808 Prevent segfault errors when the SatDiagnConc diagnostic is requested; Add SatDiagnEdge collection
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  Headers/state_diag_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.metals
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCO
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagO3
Labels: bug, never stale, diagnostics

#1682 Fix GEOS-Chem Classic parallelization errors revealed by parallelization tests - closes #1637
  CHANGELOG.md
  GeosCore/apm_driv_mod.F90
  GeosCore/carbon_mod.F90
  GeosCore/drydep_mod.F90
  GeosCore/dust_mod.F90
  GeosCore/mercury_mod.F90
  GeosCore/ocean_mercury_mod.F90
  GeosCore/seasalt_mod.F90
  GeosCore/sulfate_mod.F90
  GeosCore/wetscav_mod.F90
  Headers/state_chm_mod.F90
  Headers/state_met_mod.F90
  KPP/fullchem/fullchem_SulfurChemFuncs.F90
Labels: bug, performance / parallelization

#1852 Fix GC-Classic run directory runScriptSamples symbolic link
  run/GCClassic/createRunDir.sh
Labels: bug

#1858 Fix bug in state_chm_mod that printed line of equals signs to log from every core
  Headers/state_chm_mod.F90
Labels: bug

#1868 Rename GCHP mid-run restart files in run scripts even if run crashes
  run/GCHP/runScriptSamples/gchp.batch_job.sh
  run/GCHP/runScriptSamples/gchp.local.run
  run/GCHP/runScriptSamples/operational_examples/harvard_cannon/gchp.run
  run/GCHP/runScriptSamples/operational_examples/mit_hex/gchp.run_HEX
  run/GCHP/runScriptSamples/operational_examples/mit_svante/gchp.run_SVANTE.sh
  run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/gchp.pleiades.run
  run/GCHP/runScriptSamples/operational_examples/nci_gadi/gchp.pbs.run
  run/GCHP/runScriptSamples/operational_examples/wustl_compute1/gchp.batch_job.sh
Labels: config-files / rundir

#1870 Update the LICENSE.txt and AUTHORS.txt in geoschem/geos-chem as of July 2023
  AUTHORS.txt
  LICENSE.txt
Labels: feature, documentation

#1874 Update GCHP run files for NASA Pleiades cluster
  CHANGELOG.md
  run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/README
  run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/gchp.pleiades.env
  run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/gchp.pleiades.run
Labels: GCHP, config-files / rundir

#1876 Use standard format for AEIC 2019 monthly climatology in ExtData.rc
  CHANGELOG.md
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
Labels: GCHP, config-files / rundir, zero-diff

#1879 Add new GCHP config file for ESMF logging
  CHANGELOG.md
  run/GCHP/ESMF.rc
  run/GCHP/init_rd.sh
  run/shared/cleanRunDir.sh
Labels: GCHP, config-files / rundir, zero-diff

#1882 Convert GEOS-Chem netCDF utility routines to use the netCDF-F90 interface
  CHANGELOG.md
  NcdfUtil/m_netcdf_io_checks.F90
  NcdfUtil/m_netcdf_io_create.F90
  NcdfUtil/m_netcdf_io_define.F90
  NcdfUtil/m_netcdf_io_get_dimlen.F90
  NcdfUtil/m_netcdf_io_handle_err.F90
  NcdfUtil/m_netcdf_io_open.F90
  NcdfUtil/m_netcdf_io_read.F90
  NcdfUtil/m_netcdf_io_readattr.F90
  NcdfUtil/m_netcdf_io_write.F90
  NcdfUtil/ncdf_mod.F90
Labels: feature, structural, zero-diff

#1887 Disable SpeciesConcMND output for benchmark simulations
  CHANGELOG.md
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: diagnostics

#1890 Add fixes for transport tracers simulation
  CHANGELOG.md
  GeosCore/tracer_mod.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.TransportTracers
  run/GCHP/ExtData.rc.templates/ExtData.rc.TransportTracers
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.TransportTracers
  run/shared/species_database.yml
Labels: bug, specialty simulations
