Repository geoschem/geos-chem, pull requests merged in 2023-10, with the labels that each got.

#1976 Add fix for CH4 analytical inversions to convert state vector values read from file to nearest integer
  CHANGELOG.md
  GeosCore/global_ch4_mod.F90
Labels: bugfix, inversions

#1977 Add OH perturbation option for CH4 simulations via HEMCO
  CHANGELOG.md
  GeosCore/global_ch4_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hco_utilities_gc_mod.F90
  GeosCore/input_mod.F90
  GeosCore/set_boundary_conditions_mod.F90
  Headers/input_opt_mod.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCH4
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.carbon
Labels: Carbon gases WG

#1989 Update sample restart files for fullchem and TransportTracers to 14.2.0 benchmark files
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
Labels: config-files / rundir, bugfix

#2009 Fix broken links to CONTRIBUTING.html and SUPPORT.html in GitHub templates
  .github/ISSUE_TEMPLATE/new-feature-or-discussion.md
  .github/ISSUE_TEMPLATE/question-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, bugfix

#1959 Fix to address GCClassic failure to integrate with TOMAS when using dev/tomas branch
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: Aerosols WG, bugfix

#2011 Fix titles for 14.2.0 and 14.2.2 in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1987 Prevent POAEMISS variable from being assigned if not allocated
  CHANGELOG.md
  GeosCore/carbon_mod.F90
Labels: no-diff-to-benchmark, bugfix

#1796 Use integer flags to denote species units instead of strings
  CHANGELOG.md
  GeosCore/aero_drydep.F90
  GeosCore/aerosol_mod.F90
  GeosCore/airs_ch4_mod.F90
  GeosCore/calc_met_mod.F90
  GeosCore/carbon_mod.F90
  GeosCore/chemistry_mod.F90
  GeosCore/diagnostics_mod.F90
  GeosCore/dust_mod.F90
  GeosCore/fullchem_mod.F90
  GeosCore/gosat_ch4_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hco_utilities_gc_mod.F90
  GeosCore/linear_chem_mod.F90
  GeosCore/mercury_mod.F90
  GeosCore/mixing_mod.F90
  GeosCore/pbl_mix_mod.F90
  GeosCore/rrtmg_rad_transfer_mod.F90
  GeosCore/set_boundary_conditions_mod.F90
  GeosCore/set_global_ch4_mod.F90
  GeosCore/sulfate_mod.F90
  GeosCore/tomas_mod.F90
  GeosCore/tracer_mod.F90
  GeosCore/ucx_mod.F90
  GeosCore/vdiff_mod.F90
  GeosCore/wetscav_mod.F90
  GeosUtil/unitconv_mod.F90
  Headers/state_chm_mod.F90
  History/history_mod.F90
  Interfaces/GCHP/gchp_chunk_mod.F90
  Interfaces/GEOS/geos_CarbonInterface.F90
  ObsPack/obspack_mod.F90
Labels: feature, structural, no-diff-to-benchmark, performance / parallelization
