Repository geoschem/geos-chem, pull requests merged in 2023-11, with the labels that each got.

#2013 Fix incorrect comment on static H2O option
  GeosCore/input_mod.F90
Labels: documentation, bugfix

#1990 Add a --no-bootstrap option to integration tests to prevent switching EFYO -> CYS in HEMCO_Config.rc
  CHANGELOG.md
  test/integration/GCClassic/README.md
  test/integration/GCClassic/integrationTest.sh
  test/integration/GCClassic/integrationTestExecute.sh
  test/integration/GCHP/README.md
  test/integration/GCHP/integrationTest.sh
  test/shared/commonFunctionsForTests.sh
Labels: feature, testing / benchmarking, no-diff-to-benchmark

#2039 Improve missing ch4 emissions error message
  CHANGELOG.md
  GeosCore/set_global_ch4_mod.F90
Labels: no-diff-to-benchmark, bugfix

#2042 Add fixes to HEMCO_Config.rc for CH4 and carbon simulations
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CO2
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.Hg
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.POPs
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.metals
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagO3
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.CO2
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagO3
Labels: no-diff-to-benchmark, specialty simulations, Carbon gases WG, bugfix

#2043 Fix typos written to GCHP integration test log files
  CHANGELOG.md
  test/integration/GCHP/integrationTestCompile.sh
  test/integration/GCHP/integrationTestExecute.sh
Labels: testing / benchmarking, no-diff-to-benchmark, bugfix
