Repository geoschem/geos-chem, pull requests merged in 2023-02, with the labels that each got.

#1565 Consolidate existing integration test scripts (slurm, lsf, interactive); Add LSF capability
  CHANGELOG.md
  run/shared/cleanRunDir.sh
  test/GCClassic/README
  test/GCClassic/README.md
  test/GCClassic/commonFunctionsForTests.sh
  test/GCClassic/intTestCompile_interactive.sh
  test/GCClassic/intTestCompile_lsf.sh
  test/GCClassic/intTestCompile_slurm.sh
  test/GCClassic/intTestCreate.sh
  test/GCClassic/intTestExecute_interactive.sh
  test/GCClassic/intTestExecute_lsf.sh
  test/GCClassic/intTestExecute_slurm.sh
  test/GCClassic/intTest_interactive.sh
  test/GCClassic/intTest_lsf.sh
  test/GCClassic/intTest_slurm.sh
  test/GCClassic/integration/README.md
  test/GCClassic/integration/commonFunctionsForTests.sh
  test/GCClassic/integration/integrationTest.sh
  test/GCClassic/integration/integrationTestCompile.sh
  test/GCClassic/integration/integrationTestCreate.sh
  test/GCClassic/integration/integrationTestExecute.sh
  test/GCClassic/integration/was.README.md
  test/GCClassic/parallel/README.md
  test/GCClassic/parallel/commonFunctionsForTests.sh
  test/GCClassic/parallel/parallelTest.sh
  test/GCClassic/parallel/parallelTestCompile.sh
  test/GCClassic/parallel/parallelTestCreate.sh
  test/GCClassic/parallel/parallelTestExecute.sh
  test/GCHP/README
  test/GCHP/README.md
  test/GCHP/commonFunctionsForTests.sh
  test/GCHP/gchp.slurm.sh
  test/GCHP/intTestCompile_slurm.sh
  test/GCHP/intTestCreate.sh
  test/GCHP/intTestResults.sh
  test/GCHP/intTest_slurm.sh
  test/GCHP/integration/README.md
  test/GCHP/integration/commonFunctionsForTests.sh
  test/GCHP/integration/integrationTest.sh
  test/GCHP/integration/integrationTestCompile.sh
  test/GCHP/integration/integrationTestCreate.sh
  test/GCHP/integration/integrationTestExecute.sh
  test/README.md
  test/shared/commonFunctionsForTests.sh
Labels: feature, testing / benchmarking, structural, zero-diff

#1638 Add reminders to compile with CMake options to createRunDir.sh scripts
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
Labels: bug, config-files / rundir, zero-diff

#1644 Fix bug where writing species metadata yaml file always attempted
  CHANGELOG.md
  Headers/species_database_mod.F90
Labels: bug

#1567 Remove NcdfUtil/perl folder
  CHANGELOG.md
  NcdfUtil/README.md
  NcdfUtil/perl/.gitignore
  NcdfUtil/perl/StrTrim.pm
  NcdfUtil/perl/definitions_a1.rc
  NcdfUtil/perl/definitions_a3cld.rc
  NcdfUtil/perl/definitions_a3dyn.rc
  NcdfUtil/perl/definitions_a3mstc.rc
  NcdfUtil/perl/definitions_a3mste.rc
  NcdfUtil/perl/definitions_cn.rc
  NcdfUtil/perl/definitions_i3.rc
  NcdfUtil/perl/isCoards
  NcdfUtil/perl/ncCodeDef
  NcdfUtil/perl/ncCodeRead
  NcdfUtil/perl/ncCodeWrite
  NcdfUtil/perl/nc_chunk.pl
  NcdfUtil/perl/nc_definitions.rc
Labels: feature, structural, zero-diff

#1643 Remove LWI from carbon simulation run directories
  CHANGELOG.md
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.carbon
Labels: bug

#1633 Update rundir configuration files to point to corrected NEI day-of-week scale factors (Closes #1608)
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: bug, data sources / I-O, config-files / rundir, zero-diff

#1632 Add entries for GFAS methanol to HEMCO_Config.rc templates
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: bug, config-files / rundir, zero-diff

#1624 Archive State_Chm%H2SO4_PRDR for production rate of H2SO4 (mol/mol) for CESM-GC
  GeosCore/fullchem_mod.F90
  Headers/state_chm_mod.F90
Labels: feature, diagnostics, zero-diff, interface to external model

#1621 Apply work-around for GFAS pFe bug in GC-Classic and GCHP
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: bug, HEMCO, config-files / rundir

#1650 Simplify Github issue and pull request templates
  .github/ISSUE_TEMPLATE/ask-a-question-about-geos-chem.md
  .github/ISSUE_TEMPLATE/new-feature-or-discussion.md
  .github/ISSUE_TEMPLATE/question-issue.md
  .github/ISSUE_TEMPLATE/report-a-bug-or-technical-issue.md
  .github/ISSUE_TEMPLATE/request-a-new-feature.md
  .github/ISSUE_TEMPLATE/start-a-geos-chem-discussion.md
  .github/ISSUE_TEMPLATE/version-release-checklist.md
  .github/PULL_REQUEST_TEMPLATE/create-a-geos-chem-pull-request.md
Labels: documentation, zero-diff

#1657 Avoid compiler warning and compilation restart for KPP/fullchem/gckpp_Jacobian.F90
  CHANGELOG.md
  KPP/fullchem/CMakeLists.txt
  run/GCHP/createRunDir.sh
Labels: bug, build

#1656 Change HEMCO time cycle flag in benchmark rundir & integration tests for 14.1.1
  run/shared/setupConfigFiles.sh
  test/GCClassic/integration/integrationTestExecute.sh
  test/GCClassic/parallel/parallelTestExecute.sh
  test/GCHP/integration/integrationTestExecute.sh
Labels: feature, testing / benchmarking

#1663 Fix incorrect comparison in GET_IJ routine; Fix leftover issues from PR #1656
  CHANGELOG.md
  GeosUtil/gc_grid_mod.F90
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
  run/shared/setupConfigFiles.sh
  test/GCClassic/integration/integrationTestExecute.sh
  test/GCClassic/parallel/parallelTestExecute.sh
  test/GCHP/integration/integrationTestExecute.sh
Labels: bug

#1674 Ask users for PI at registration; abstract user registration code into a single script
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
  run/shared/newUserRegistration.sh
  test/shared/commonFunctionsForTests.sh
Labels: feature, config-files / rundir
