Repository geoschem/geos-chem, pull requests merged in 2024-03, with the labels that each got.

#2176 UCX bug fixes : (1) Use proper 4th index for WERADIUS array; (2) Get density of black carbon from the species database
  CHANGELOG.md
  GeosCore/ucx_mod.F90
Labels: KPP / chem mechanisms, bugfix

#2178 Rename "native" to "raw" in GCHP run directory creation scripts & templates
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.gmao_metfields
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/createRunDir.sh
  run/GCHP/init_rd.sh
  run/shared/settings/geosfp/geosfp.derived_1hr_wind_cs.txt
  run/shared/settings/geosfp/geosfp.native_1hr_mass_flux_cs.txt
  run/shared/settings/geosfp/geosfp.preprocessed_ll.txt
  run/shared/settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt
  run/shared/settings/geosfp/geosfp.raw_3hr_wind_ll.txt
  run/shared/settings/geosfp/geosfp.raw_ll.txt
  run/shared/settings/geosit/discover/geosit.raw_cs.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_ll.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_mass_flux.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_wind_cs.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_wind_ll.discover.txt
  run/shared/settings/geosit/geosit.preprocessed_ll.txt
  run/shared/settings/geosit/geosit.raw_cs.txt
  run/shared/settings/geosit/geosit.raw_ll.txt
  run/shared/settings/geosit/geosit.raw_mass_flux.txt
  run/shared/settings/geosit/geosit.raw_wind_cs.txt
  run/shared/settings/geosit/geosit.raw_wind_ll.txt
  run/shared/settings/merra2.txt
Labels: feature, GCHP, config-files / rundir, structural, no-diff-to-benchmark

#2198 Update volcano emissions through the end of 2022
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
Labels: Emissions WG

#2154 Updates for GEOS-Chem 14.3 in CESM
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
  GeosCore/fast_jx_mod.F90
  GeosCore/input_mod.F90
  GeosCore/photolysis_mod.F90
  GeosCore/ucx_mod.F90
  Headers/input_opt_mod.F90
  run/CESM/HEMCO_Config.rc
  run/CESM/HEMCO_Diagn.rc
  run/CESM/HISTORY.rc
  run/CESM/geoschem_config.yml
  run/CESM/util/README
  run/CESM/util/dep_data_file.cdl
Labels: structural, no-diff-to-benchmark, interface to external model, CESM-GC

#2205 Fix uptake coefficients on stratospheric aerosol
  KPP/fullchem/commonIncludeVars.H
  KPP/fullchem/fullchem_RateLawFuncs.F90
Labels: KPP / chem mechanisms, Strat WG, bugfix

#2207 Fix bug for SLP and TROPP scaling
  CHANGELOG.md
  run/shared/settings/geosfp/geosfp.preprocessed_ll.txt
  run/shared/settings/geosit/geosit.preprocessed_ll.txt
Labels: config-files / rundir, no-diff-to-benchmark, bugfix

#2078 Fix PBL level calculations
  GeosCore/pbl_mix_mod.F90
  Headers/state_met_mod.F90
Labels: feature, never stale

#2211 Initialize PBL variables
  GeosCore/pbl_mix_mod.F90
Labels: bugfix

#2213 Change NEI 2D emissions to xy dimension
  CHANGELOG.md
  run/CESM/HEMCO_Config.rc
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/WRF/fullchem/HEMCO_Config.rc
Labels: HEMCO, config-files / rundir, bugfix

#2222 Update integration tests to pass quick option to compile scripts
  CHANGELOG.md
  test/integration/GCClassic/integrationTest.sh
  test/integration/GCClassic/integrationTestCompile.sh
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCHP/integrationTest.sh
  test/integration/GCHP/integrationTestCompile.sh
  test/integration/GCHP/integrationTestCreate.sh
Labels: feature, testing / benchmarking

#2224 Fix geopotential height units in netCDF file
  Headers/state_met_mod.F90
Labels: no-diff-to-benchmark, bugfix, math / units

#2199 Add GCHP diagnostics for GCHPctmEnv and FV3 gridded components
  CHANGELOG.md
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/setCommonRunSettings.sh.template
Labels: feature, GCHP, diagnostics

#2218 Add updates for CH4 analytical inversion
  CHANGELOG.md
  GeosCore/carbon_gases_mod.F90
  GeosCore/emissions_mod.F90
  GeosCore/global_ch4_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/input_mod.F90
  Headers/species_database_mod.F90
  Headers/state_chm_mod.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCH4
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: category: Feature Request, topic: Specialty Simulations, Attn: Carbon gases WG, topic: Analytical Inversions

#2226 Fix bug in transport tracer pressure mask criteria affecting tracer st80_25
  CHANGELOG.md
  GeosCore/tracer_mod.F90
Labels: category: Bug, Attn: Transport WG, topic: TransportTracers Simulation

#2225 Remove requirement for photolysis data directories to end with slash
  CHANGELOG.md
  GeosCore/photolysis_mod.F90
Labels: category: Feature Request, topic: Structural Modifications, no-diff-to-benchmark

#2228 Update CH4 emissions from EDGARv7 to EDGARv8
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCH4
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: category: Feature Request, no-diff-to-benchmark, Attn: Carbon gases WG, topic: Carbon Gases Simulations
