Repository geoschem/geos-chem, pull requests merged in 2024-07, with the labels that each got.

#2359 Allow per-species definition of KPP absolute and relative solver tolerances; Set absolute tolerances of dummy species to large value
  CHANGELOG.md
  GeosCore/fullchem_mod.F90
  GeosCore/mercury_mod.F90
  Headers/roundoff_mod.F90
  Headers/species_database_mod.F90
  Headers/species_mod.F90
  Headers/state_chm_mod.F90
  run/shared/species_database.yml
  run/shared/species_database_hg.yml
Labels: topic: Chemical Mechanisms, Attn: Chemistry WG, category: Bug Fix

#2342 Read number of levels with clouds used in photolysis from config file
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
  GeosCore/input_mod.F90
  Headers/input_opt_mod.F90
  run/CESM/geoschem_config.yml
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GEOS/geoschem_config.yml
  run/WRF/fullchem/geoschem_config.yml
  run/shared/settings/geosfp/geosfp.preprocessed_ll.txt
  run/shared/settings/geosfp/geosfp.raw_ll.txt
  run/shared/settings/geosit/discover/geosit.raw_cs.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_ll.discover.txt
  run/shared/settings/geosit/geosit.preprocessed_ll.txt
  run/shared/settings/geosit/geosit.raw_cs.txt
  run/shared/settings/geosit/geosit.raw_ll.txt
  run/shared/settings/merra2.txt
  run/shared/settings/modele2.1.txt
Labels: topic: Configuration Files, category: Bug Fix

#2353 Cloud-J error handling
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
Labels: category: Feature Request, topic: Structural Modifications

#2366 Changes for coupling GEOS-Chem to CESM in Spectral-element Dynamical Core (CAM-SE)
  CHANGELOG.md
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/photolysis_mod.F90
  GeosCore/ucx_mod.F90
  Headers/state_grid_mod.F90
Labels: category: Interface to External Model, topic: CESM

#2369 Fix several issues with the GEOS-Chem Classic satellite diagnostics (SatDiagn and SatDiagnEdge collections)
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  History/history_mod.F90
  History/history_netcdf_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.metals
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCO
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagO3
Labels: topic: Diagnostics, category: Bug Fix

#2372 Turn off the MEGAN extension for fullchem "non-benchmark" simulations
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/createRunDir.sh
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/createRunDir.sh
Labels: topic: Configuration Files, no-diff-to-benchmark, category: Bug Fix, topic: Run Directories

#2375 Update standard emissions in CESM to match standard model
  CHANGELOG.md
  run/CESM/HEMCO_Config.rc
Labels: category: Interface to External Model, topic: CESM

#2394 Add ModelE2.1 (GCAP 2.0) simulation to GCClassic integration tests
  CHANGELOG.md
  test/integration/GCClassic/integrationTestCreate.sh
  test/shared/commonFunctionsForTests.sh
Labels: category: Feature Request, topic: Benchmarking and Testing, topic: GCAP2 Meteorology

#2398 Pass non-zero Ca2, Mg, and K cations to HETP
  CHANGELOG.md
  GeosCore/aerosol_thermodynamics_mod.F90
Labels: category: Feature Request, Attn: Aerosols WG, topic: Aerosols
