Repository geoschem/geos-chem, pull requests merged in 2024-09, with the labels that each got.

#2424 Support for Cloud-J version 8.0.0
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
  GeosCore/input_mod.F90
  Headers/input_opt_mod.F90
  run/CESM/geoschem_config.yml
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GEOS/geoschem_config.yml
  run/WRF/fullchem/geoschem_config.yml
Labels: Attn: Chemistry WG, topic: Photolysis

#2426 Store aerosol-specific optics files in new Aerosol_Optics data directory
  CHANGELOG.md
  GeosCore/aerosol_mod.F90
  GeosCore/fjx_interface_mod.F90
  GeosCore/gc_environment_mod.F90
  GeosCore/input_mod.F90
  GeosCore/photolysis_mod.F90
  Headers/input_opt_mod.F90
  run/CESM/geoschem_config.yml
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GEOS/geoschem_config.yml
  run/WRF/fullchem/geoschem_config.yml
Labels: category: Feature Request, topic: Structural Modifications, no-diff-to-benchmark

#2452 Bug fix: Reorder photo rxns for PNs and ANs (from PR #2318)
  CHANGELOG.md
  KPP/custom/custom.eqn
  KPP/fullchem/fullchem.eqn
  KPP/fullchem/gckpp_Function.F90
  KPP/fullchem/gckpp_Jacobian.F90
  KPP/fullchem/gckpp_Monitor.F90
  KPP/fullchem/gckpp_Rates.F90
Labels: category: Bug Fix, topic: Photolysis

#2457 Update `Is_Photolysis` tags in `species_database.yml` to be consistent with Cloud-J file `FJX_j2j.dat`
  CHANGELOG.md
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/shared/species_database.yml
Labels: topic: Configuration Files, topic: Chemical Mechanisms, category: Bug Fix, topic: Photolysis

#2430 Updated soil NOx scheme from Yi Wang et al. (2021) as an option
  CHANGELOG.md
  GeosCore/flexgrid_read_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  Headers/input_opt_mod.F90
  Headers/state_met_mod.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.gmao_metfields
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: category: Feature Request, no-diff-to-benchmark, Attn: Emissions WG, topic: Emissions

#2462 Bug fix: ALK6 in HEMCO_Config.rc should be ALK7
  run/CESM/HEMCO_Config.rc
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/WRF/fullchem/HEMCO_Config.rc
  run/WRF/fullchem/HEMCO_Diagn.rc
Labels: category: Bug Fix

#2464 Remove J-value diagnostics which are all zero
  CHANGELOG.md
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/shared/species_database.yml
Labels: category: Bug, topic: Diagnostics

#2467 Fix dry mass fraction of seasalt in aerosol thermodynamics
  CHANGELOG.md
  GeosCore/aerosol_thermodynamics_mod.F90
Labels: category: Bug Fix, topic: Aerosols

#2477 Bug fix for double counting CH4 agricultural burning emissions
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: category: Bug Fix, topic: Carbon Gases Simulations

#2473 Add seasonality to CH4 reservoir emissions
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: category: Feature Request, Attn: Carbon gases WG, topic: Carbon Gases Simulations

#2472 Bugfix: Restore stale workflow functionality
  .github/workflows/stale.yml
  CHANGELOG.md
Labels: category: Bug Fix, topic: GitHub
