Repository geoschem/geos-chem, pull requests merged in 2024-11, with the labels that each got.

#2555 Dry run updates for GEOS-Chem Classic 14.5.0
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
  run/GCHP/createRunDir.sh
  run/shared/download_data.py
  run/shared/download_data.yml
Labels: category: Feature Request, topic: Dry-Run Simulation, no-diff-to-benchmark

#2562 Update version number to 14.5.0 in CHANGELOG.md
  CHANGELOG.md
Labels: TODO: Documentation

#2482 KPP standalone interface from Obin Sturm
  .gitignore
  CHANGELOG.md
  GeosCore/CMakeLists.txt
  GeosCore/fullchem_mod.F90
  GeosCore/kppsa_interface_mod.F90
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
  run/shared/cleanRunDir.sh
  run/shared/kpp_standalone_interface.yml
Labels: category: Feature Request, topic: Chemical Mechanisms, no-diff-to-benchmark, Topic: Fullchem Simulations

#2486 Prevent segmentation fault in qfyaml with some compilers
  CHANGELOG.md
  Headers/qfyaml_mod.F90
Labels: category: Bug, topic: Configuration Files, topic: Runtime Error

#2578 Some fixes required to compile adjoint geos chem
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  GeosUtil/unitconv_mod.F90
  Interfaces/GCHP/Chem_GridCompMod.F90
  Interfaces/GCHP/gchp_chunk_mod.F90
Labels: topic: Adjoint Model, category: Bug Fix

#2593 Prevent History diagnostic collection duration from being shorter than frequency
  CHANGELOG.md
  History/history_mod.F90
Labels: topic: Diagnostics, no-diff-to-benchmark, category: Bug Fix
