Repository geoschem/geos-chem, pull requests merged in 2024-08, with the labels that each got.

#2352 Add fixes for ALK4 and R4N2 chemistry from Brewer et al. (2023, JGR)
  CHANGELOG.md
  KPP/custom/custom.eqn
  KPP/fullchem/CHANGELOG_fullchem.md
  KPP/fullchem/fullchem.eqn
  KPP/fullchem/fullchem.kpp
  run/shared/species_database.yml
Labels: topic: Chemical Mechanisms, Attn: Chemistry WG, category: Bug Fix

#2399 Add simulation with all diagnostics turned to integration testing
  CHANGELOG.md
  GeosCore/planeflight_mod.F90
  Headers/state_diag_mod.F90
  Interfaces/GCHP/gchp_historyexports_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CO2
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.POPs
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.TransportTracers
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.metals
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCO
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagO3
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  test/integration/GCClassic/integrationTestCompile.sh
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCClassic/integrationTestExecute.sh
  test/integration/GCHP/integrationTestCompile.sh
  test/integration/GCHP/integrationTestCreate.sh
  test/integration/GCHP/integrationTestExecute.sh
  test/shared/alldiags/Planeflight.dat.20190701
  test/shared/commonFunctionsForTests.sh
Labels: topic: Benchmarking and Testing, no-diff-to-benchmark

#2410 Add tropopause pressure to the GEOS-Chem Classic "SatDiagn" collection
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  Headers/state_diag_mod.F90
Labels: category: Feature Request, topic: Diagnostics, no-diff-to-benchmark

#2397 Add GC-Classic transport tracer global half-degree run option with GEOS-IT
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
Labels: category: Feature Request, no-diff-to-benchmark, topic: Run Directories

#2402 Fixes for HEMCO diagnostic config file HEMCO_Diagn.rc
  CHANGELOG.md
  run/GCClassic/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCHP/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCHP/setCommonRunSettings.sh.template
Labels: topic: Diagnostics, category: Bug Fix, topic: Emissions

#2425 Merge GEOS-Chem 14.4.3 into the 14.5.0 development branch
  .github/workflows/stale.yml
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  GeosCore/planeflight_mod.F90
  GeosCore/sulfate_mod.F90
  Headers/state_diag_mod.F90
  Interfaces/GCHP/gchp_historyexports_mod.F90
  run/GCClassic/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/createRunDir.sh
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CO2
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.POPs
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.TransportTracers
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.metals
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCO
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagO3
  run/GCHP/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/setCommonRunSettings.sh.template
  test/integration/GCClassic/integrationTestCompile.sh
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCClassic/integrationTestExecute.sh
  test/integration/GCHP/integrationTestCompile.sh
  test/integration/GCHP/integrationTestCreate.sh
  test/integration/GCHP/integrationTestExecute.sh
  test/shared/alldiags/Planeflight.dat.20190701
  test/shared/commonFunctionsForTests.sh
Labels: category: Feature Request, no-diff-to-benchmark

#2144 Restore dry deposition output in GCHP & GCClassic fullchem benchmark simulations
  CHANGELOG.md
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: category: Feature Request, topic: Diagnostics, topic: Benchmarking and Testing

#2428 Fix mass non-conservation in VDIFF PBL mixing
  CHANGELOG.md
  GeosCore/global_ch4_mod.F90
  GeosCore/vdiff_mod.F90
Labels: category: Bug Fix, topic: Convection and Mixing

#2436 Update GFED4_Climatology entries for period 2010-2023 with new species
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: category: Feature Request, topic: Configuration Files, no-diff-to-benchmark, topic: Emissions

#2439 Update run scripts and environment files for NASA discover cluster
  CHANGELOG.md
  run/GCClassic/runScriptSamples/operational_examples/nasa_discover/gcc.discover.build
  run/GCClassic/runScriptSamples/operational_examples/nasa_discover/gcc.discover.run
  run/GCClassic/runScriptSamples/operational_examples/nasa_discover/gcc.spack-stack-1.6.0.env
  run/GCClassic/runScriptSamples/operational_examples/nasa_discover/gcc.spack-stack-1.7.0-gnu.milan.env
  run/GCClassic/runScriptSamples/operational_examples/nasa_discover/gcc.spack-stack-1.7.0-intel.milan.env
  run/GCHP/runScriptSamples/operational_examples/nasa_discover/gchp.discover.build
  run/GCHP/runScriptSamples/operational_examples/nasa_discover/gchp.discover.run
  run/GCHP/runScriptSamples/operational_examples/nasa_discover/gchp.spack-stack-1.6.0.env
  run/GCHP/runScriptSamples/operational_examples/nasa_discover/gchp.spack-stack-1.7.0-gnu.milan.env
  run/GCHP/runScriptSamples/operational_examples/nasa_discover/gchp.spack-stack-1.7.0-intel.milan.env
Labels: category: Feature Request, topic: User Environment, no-diff-to-benchmark
