Repository geoschem/geos-chem, pull requests merged in 2025-03, with the labels that each got.

#2757 GEOS-Chem (science codebase) 14.5.3 release
  CHANGELOG.md
  run/CESM/HEMCO_Config.rc
Labels: category: Feature Request, topic: Releases

#2756 Fixed incorrect description metadata for FluxHg0FromOceanToAir and FluxHg0FromAirToOcean diagnostics
  CHANGELOG.md
  Headers/state_diag_mod.F90
Labels: topic: Diagnostics, no-diff-to-benchmark, category: Bug Fix

#2766 Update KPP/CMakeLists.txt to only compile KPP-Standalone if configured with -DKPPSA=y
  CHANGELOG.md
  KPP/CMakeLists.txt
Labels: topic: Chemical Mechanisms, topic: Structural Modifications, no-diff-to-benchmark, category: Bug Fix

#2703 Aerosol table updates for mineral dust
  CHANGELOG.md
  GeosCore/input_mod.F90
  run/CESM/geoschem_config.yml
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.Hg
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.aerosol
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.fullchem
  run/GEOS/geoschem_config.yml
  run/WRF/fullchem/geoschem_config.yml
Labels: category: Feature Request, topic: Configuration Files, topic: Aerosols

#2772 Fix error in download_data.py causing data to be downloaded one directory level too high
  CHANGELOG.md
  run/shared/download_data.py
Labels: topic: Dry-Run Simulation, no-diff-to-benchmark, category: Bug Fix

#2749 Retrieve arrays needed in Cloud-J to correctly set UV Flux diagnostics
  CHANGELOG.md
  GeosCore/cldj_interface_mod.F90
Labels: topic: Diagnostics, category: Bug Fix

#2779 Add SatDiagnPMID diagnostic to save pressure at level midpoints for the SatDiagn collection
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  Headers/state_diag_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.metals
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCO
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagO3
Labels: category: Feature Request, topic: Diagnostics

#2752 Rebuild chemical mechanisms with KPP 3.2.0; Also set KPP 3.2.0 as the minimum required version
  CHANGELOG.md
  KPP/Hg/Hg.kpp
  KPP/Hg/gckpp_Function.F90
  KPP/Hg/gckpp_Global.F90
  KPP/Hg/gckpp_Initialize.F90
  KPP/Hg/gckpp_Integrator.F90
  KPP/Hg/gckpp_Jacobian.F90
  KPP/Hg/gckpp_JacobianSP.F90
  KPP/Hg/gckpp_LinearAlgebra.F90
  KPP/Hg/gckpp_Monitor.F90
  KPP/Hg/gckpp_Parameters.F90
  KPP/Hg/gckpp_Rates.F90
  KPP/Hg/gckpp_Util.F90
  KPP/carbon/carbon.kpp
  KPP/carbon/gckpp_Function.F90
  KPP/carbon/gckpp_Global.F90
  KPP/carbon/gckpp_Initialize.F90
  KPP/carbon/gckpp_Integrator.F90
  KPP/carbon/gckpp_Jacobian.F90
  KPP/carbon/gckpp_LinearAlgebra.F90
  KPP/carbon/gckpp_Monitor.F90
  KPP/carbon/gckpp_Parameters.F90
  KPP/carbon/gckpp_Rates.F90
  KPP/carbon/gckpp_Util.F90
  KPP/custom/custom.kpp
  KPP/fullchem/fullchem.kpp
  KPP/fullchem/gckpp_Function.F90
  KPP/fullchem/gckpp_Global.F90
  KPP/fullchem/gckpp_Initialize.F90
  KPP/fullchem/gckpp_Integrator.F90
  KPP/fullchem/gckpp_Jacobian.F90
  KPP/fullchem/gckpp_JacobianSP.F90
  KPP/fullchem/gckpp_LinearAlgebra.F90
  KPP/fullchem/gckpp_Monitor.F90
  KPP/fullchem/gckpp_Parameters.F90
  KPP/fullchem/gckpp_Rates.F90
  KPP/fullchem/gckpp_Util.F90
Labels: category: Feature Request, topic: Chemical Mechanisms, topic: Structural Modifications, no-diff-to-benchmark

#1980 Add capability to run GEOS-Chem Classic at 0.125x0.15625 resolution (nested-grid simulations only)
  CHANGELOG.md
  GeosCore/flexgrid_read_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/input_mod.F90
  GeosCore/pjc_pfix_window_mod.F90
  GeosCore/sulfate_mod.F90
  GeosCore/tomas_mod.F90
  GeosCore/tpcore_window_mod.F90
  GeosUtil/time_mod.F90
  Interfaces/GCClassic/main.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.gmao_metfields_0125
  run/GCClassic/createRunDir.sh
  run/shared/settings/0125x015625.txt
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCClassic/integrationTestExecute.sh
  test/shared/commonFunctionsForTests.sh
Labels: category: Feature Request, topic: Input Data, topic: Nested Grid Simulation, never stale, topic: Structural Modifications, no-diff-to-benchmark

#2786 Fix issues causing fullchem_alldiags integration tests to differ; Fix incorrect file paths in download_data.py
  CHANGELOG.md
  ObsPack/obspack_mod.F90
  run/shared/download_data.py
  test/integration/GCClassic/integrationTestCreate.sh
Labels: topic: Dry-Run Simulation, topic: Benchmarking and Testing, no-diff-to-benchmark, category: Bug Fix

#2791 Add MODEL_BCC to enable BCC-GEOS-Chem v2.0
  CHANGELOG.md
  GeosCore/aerosol_mod.F90
  GeosCore/calc_met_mod.F90
  GeosCore/linear_chem_mod.F90
  GeosCore/sulfate_mod.F90
  GeosUtil/pressure_mod.F90
Labels: topic: Structural Modifications, no-diff-to-benchmark, category: Interface to External Model
