Repository geoschem/geos-chem, pull requests merged in 2025-05, with the labels that each got.

#2841 Restore UVFlux collection in the GCHP fullchem_alldiags int test
  CHANGELOG.md
  test/integration/GCHP/integrationTestCreate.sh
Labels: topic: Benchmarking and Testing, no-diff-to-benchmark, category: Bug Fix

#2840 Fix ExtData entry for GFED4 daily frac
  CHANGELOG.md
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
Labels: topic: Configuration Files, no-diff-to-benchmark, category: Bug Fix, topic: Emissions

#2837 Fix entries for GEOS-IT preprocessed cubed-sphere wind in GCHP
  CHANGELOG.md
  run/shared/settings/geosit/geosit.preprocessed_wind_cs.txt
Labels: topic: GCHP, topic: Input Data, no-diff-to-benchmark, category: Bug Fix, topic: Run Directories

#2836 Add entry for GFAS methanol for ExtData
  CHANGELOG.md
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
Labels: topic: GCHP, topic: Configuration Files, no-diff-to-benchmark, category: Bug Fix

#2847 Add RxnRate, RxnConst and KppDiags diagnostics to the carbon and Hg simulations
  CHANGELOG.md
  GeosCore/carbon_gases_mod.F90
  GeosCore/mercury_mod.F90
  Headers/state_diag_mod.F90
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.carbon
Labels: topic: Chemical Mechanisms, topic: Diagnostics, category: Bug Fix

#2853 Modify ObsPack I/O to look for "middle" or "midpoint" in the "time:comment" field
  CHANGELOG.md
  ObsPack/obspack_mod.F90
Labels: topic: Diagnostics, no-diff-to-benchmark, category: Bug Fix

#2869 Remove setting DELP_DRY to zero when not found in restart file
  CHANGELOG.md
  GeosCore/hco_utilities_gc_mod.F90
Labels: no-diff-to-benchmark, category: Bug Fix, topic: Restart Files
