Repository geoschem/geos-chem, pull requests merged in 2025-01, with the labels that each got.

#2669 Implement Australian Hg emissions inventory (2010-2019) from MacFarlane et al. [2022]
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.Hg
Labels: category: Feature Request, topic: Configuration Files, no-diff-to-benchmark, topic: Hg or POPs simulations, topic: Emissions

#2670 Add comments to GCClassic HISTORY.rc template files advising users not to change BoundaryConditions.frequency
  CHANGELOG.md
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CH4
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.CO2
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.POPs
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.TransportTracers
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.aerosol
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.carbon
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.metals
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagCO
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.tagO3
Labels: topic: Configuration Files, no-diff-to-benchmark, category: Bug Fix

#2554 Bug fixes for the carbon simulations in GCClassic and GCHP
  CHANGELOG.md
  GeosCore/carbon_gases_mod.F90
  GeosCore/input_mod.F90
  KPP/carbon/carbon_Funcs.F90
  KPP/carbon/gckpp_Function.F90
  KPP/carbon/gckpp_Global.F90
  KPP/carbon/gckpp_Initialize.F90
  KPP/carbon/gckpp_Integrator.F90
  KPP/carbon/gckpp_Jacobian.F90
  KPP/carbon/gckpp_LinearAlgebra.F90
  KPP/carbon/gckpp_Monitor.F90
  KPP/carbon/gckpp_Parameters.F90
  KPP/carbon/gckpp_Rates.F90
  KPP/carbon/gckpp_Util.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
  run/GCClassic/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CO2
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.tagCO
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HEMCO_Diagn.rc.templates/HEMCO_Diagn.rc.carbon
  run/GCHP/geoschem_config.yml.templates/geoschem_config.yml.carbon
  run/shared/singleCarbonSpecies.sh
Labels: no-diff-to-benchmark, category: Bug Fix, topic: Carbon Gases Simulations

#2674 Change default environment files for integration tests on Harvard Cannon from gnu10 to gnu12
  CHANGELOG.md
  test/shared/commonFunctionsForTests.sh
Labels: topic: Benchmarking and Testing, no-diff-to-benchmark, category: Bug Fix

#2675 Fixed the problem that GCHP cannot read meteorology field from yaml
  GeosCore/input_mod.F90
Labels: topic: GCHP, topic: Configuration Files, category: Bug Fix

#2683 Restore updates for TMB emissions that were clobbered whem 14.5.1 was merged into dev/14.6.0
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: topic: Configuration Files, category: Bug Fix, topic: Emissions

#2690 Add .zenodo.json to auto-populate DOI fields upon version releases
  .zenodo.json
  CHANGELOG.md
Labels: no-diff-to-benchmark, category: Bug Fix

#2171 Add CEDS 0.1 x 0.1 degree emissions
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
  run/GCHP/ExtData.rc.templates/ExtData.rc.TransportTracers
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/ExtData.rc.templates/ExtData.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.TransportTracers
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: category: Feature Request, topic: Input Data, topic: Configuration Files, topic: Emissions

#2684 Fix CO2 weekly scale factors entry in GCHP ExtData.rc for carbon simulation
  CHANGELOG.md
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
Labels: topic: GCHP, topic: Configuration Files, no-diff-to-benchmark, category: Bug Fix

#2673 Implement GRPI CH4 rice emissions to replace EDGAR in CH4 and carbon simulations
  CHANGELOG.md
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
  run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.carbon
Labels: category: Feature Request, topic: Carbon Gases Simulations, topic: Emissions

#2512 Update dust scale factors for Dust DEAD using meteorlogy friction velocity
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
Labels: topic: Configuration Files, category: Bug Fix, topic: Emissions

#2616 Add run directory creation support for processed cubed-sphere GEOS-IT meteorology
  CHANGELOG.md
  run/GCHP/createRunDir.sh
  run/shared/settings/geosfp/geosfp.preprocessed_ll.txt
  run/shared/settings/geosfp/geosfp.raw_ll.txt
  run/shared/settings/geosit/discover/geosit.raw_cs.discover.txt
  run/shared/settings/geosit/discover/geosit.raw_ll.discover.txt
  run/shared/settings/geosit/geosit.preprocessed_cs.txt
  run/shared/settings/geosit/geosit.preprocessed_ll.txt
  run/shared/settings/geosit/geosit.preprocessed_mass_flux.txt
  run/shared/settings/geosit/geosit.preprocessed_wind_cs.txt
  run/shared/settings/geosit/geosit.raw_cs.txt
  run/shared/settings/geosit/geosit.raw_ll.txt
  run/shared/settings/merra2.txt
  run/shared/settings/modele2.1.txt
Labels: category: Feature Request, topic: GCHP, topic: Run Directories
