Repository geoschem/geos-chem, pull requests merged in 2025-02, with the labels that each got.

#2712 Do not build KPP-Standalone executable unless specifically requested at compile time
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
  test/integration/GCClassic/integrationTestCreate.sh
  test/integration/GCHP/integrationTestCreate.sh
  test/parallel/GCClassic/parallelTestCreate.sh
Labels: category: Feature Request, topic: Build, no-diff-to-benchmark

#2711 Apply retuned dust scale factors for MERRA2 C24, GEOSFP C24, and GEOSIT C24 grids
  CHANGELOG.md
  run/GCHP/setCommonRunSettings.sh.template
  run/GEOS/HEMCO_Config.rc
Labels: topic: GCHP, category: Bug Fix, topic: Emissions

#2689 Set a C-preprocessor switch so that we can block out code specific to the KPP rosenbrock_autoreduce integrator
  CHANGELOG.md
  GeosCore/fullchem_mod.F90
  KPP/Hg/CMakeLists.txt
  KPP/carbon/CMakeLists.txt
  KPP/custom/CMakeLists.txt
  KPP/fullchem/CMakeLists.txt
  KPP/fullchem/fullchem_AutoReduceFuncs.F90
  KPP/stubs/stub_fullchem_AutoReduceFuncs.F90
Labels: category: Feature Request, topic: Chemical Mechanisms, topic: Structural Modifications, no-diff-to-benchmark

#2723 Fix typo: KPP_INTEGERATOR_AUTOREDUCE -> KPP_INTEGRATOR_AUTOREDUCE (bug from PR #2689)
  CHANGELOG.md
  GeosCore/fullchem_mod.F90
Labels: topic: Chemical Mechanisms, no-diff-to-benchmark, category: Bug Fix

#2709 Remove goto statements in drydep_mod.F90
  CHANGELOG.md
  GeosCore/drydep_mod.F90
Labels: category: Feature Request, topic: Structural Modifications, no-diff-to-benchmark

#2727 Fix bug in drydep_mod from PR #2709 by moving ENDIF further down in routine DEPVEL
  GeosCore/drydep_mod.F90
Labels: category: Bug Fix, topic: Deposition

#2717 Now define the dry deposition land cover type properly for O3 deposition to oceans
  CHANGELOG.md
  GeosCore/drydep_mod.F90
Labels: category: Bug Fix, topic: Deposition

#2573 Fixed PDOWN definition and re-evaporation requirement for washout
  CHANGELOG.md
  GeosCore/convection_mod.F90
Labels: category: Bug, topic: Convection and Mixing

#2521 Fixes towards achieving bit-for-bit reproducibility in GC-Classic upon restart
  CHANGELOG.md
  GeosCore/airs_ch4_mod.F90
  GeosCore/diagnostics_mod.F90
  GeosCore/get_ndep_mod.F90
  GeosCore/gosat_ch4_mod.F90
  GeosCore/hco_interface_gc_mod.F90
  GeosCore/hco_utilities_gc_mod.F90
  GeosCore/mixing_mod.F90
  GeosCore/planeflight_mod.F90
  GeosCore/tccon_ch4_mod.F90
  GeosCore/ucx_mod.F90
  GeosCore/wetscav_mod.F90
  GeosUtil/CMakeLists.txt
  GeosUtil/print_mod.F90
  Headers/state_chm_mod.F90
  Headers/state_diag_mod.F90
  Headers/state_met_mod.F90
  Interfaces/GCClassic/main.F90
  ObsPack/obspack_mod.F90
  run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
  run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem
Labels: topic: Structural Modifications, category: Bug Fix, topic: Restart Files

#2721 Now allow RxnRate and RxnConst to use four-digit reaction numbers
  CHANGELOG.md
  Headers/state_diag_mod.F90
  run/CESM/HISTORY.rc
  run/GCClassic/HISTORY.rc.templates/HISTORY.rc.fullchem
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem
Labels: topic: Chemical Mechanisms, topic: Diagnostics, category: Bug Fix

#2739 Fix bugs in fixed level and PBL budget diagnostics
  CHANGELOG.md
  GeosCore/diagnostics_mod.F90
  Headers/state_diag_mod.F90
Labels: topic: Diagnostics, no-diff-to-benchmark, category: Bug Fix

#2713 Read AEIC2019 emissions every timestep in CESM
  CHANGELOG.md
  run/CESM/HEMCO_Config.rc
Labels: category: Bug, topic: Configuration Files, category: Interface to External Model
