Repository geoschem/geos-chem, pull requests merged in 2025-07, with the labels that each got.

#2915 Eliminate some computational inefficiencies in convection and mixing
  CHANGELOG.md
  GeosCore/calc_met_mod.F90
  GeosCore/convection_mod.F90
  GeosCore/vdiff_mod.F90
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/gcclassic.gcc14_cannon_rocky.env
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/geoschem.vtune-hotspots.run
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/geoschem.vtune-perf-snapshot.run
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/geoschem.vtune-threading.run
  run/GCClassic/runScriptSamples/operational_examples/harvard_cannon/geoschem.vtune-uarch-explore.run
Labels: category: Feature Request, topic: Structural Modifications, no-diff-to-benchmark, topic: Performance

#2942 add unit checks for 0th hour bcs
  History/history_mod.F90
Labels: topic: Nested Grid Simulation, no-diff-to-benchmark, category: Bug Fix, topic: Math and Units

#2941 Restore missing HEMCO manual diagnostics needed for APM simulations
  CHANGELOG.md
  GeosCore/carbon_mod.F90
  GeosCore/hcoi_gc_diagn_mod.F90
Labels: no-diff-to-benchmark, category: Bug Fix, topic: Aerosols

#2944 Reorder code so that aerosol optics file paths print to dry-run log
  CHANGELOG.md
  GeosCore/aerosol_mod.F90
  GeosCore/gc_environment_mod.F90
Labels: topic: Dry-Run Simulation, no-diff-to-benchmark, category: Bug Fix

#2947 Fix typo in carbon_mod.F90 for APM simulations
  GeosCore/carbon_mod.F90
Labels: no-diff-to-benchmark, category: Bug Fix, topic: Aerosols

#2952 GCHP carbon simulation diagnostic fixes
  CHANGELOG.md
  run/GCHP/HISTORY.rc.templates/HISTORY.rc.carbon
Labels: topic: GCHP, no-diff-to-benchmark, category: Bug Fix, topic: Carbon Gases Simulations

#2965 Update met guidance in run directory creation
  CHANGELOG.md
  run/GCClassic/createRunDir.sh
  run/GCHP/createRunDir.sh
Labels: category: Feature Request, no-diff-to-benchmark, topic: Run Directories

#2969 Bugfix/update gchp mass flux cn scalings
  CHANGELOG.md
  run/GCHP/setCommonRunSettings.sh.template
Labels: topic: GCHP, topic: Input Data, topic: Configuration Files, category: Bug Fix

#2970 Update carbon simulation restart files for 14.6.3 release
  CHANGELOG.md
  run/GCHP/createRunDir.sh
  run/shared/download_data.yml
Labels: category: Feature Request, topic: Configuration Files, no-diff-to-benchmark, topic: Carbon Gases Simulations
